services:
  - type: web
    name: shifa-platform-setif
    env: node
    plan: free
    buildCommand: npm install --production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
